{% set name = "vois" %}
{% set version = "1.0.40" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vois-{{ version }}.tar.gz
  sha256: 788a4144f70e3c981107f6505ae0893e998ae9980d6bf3dcfade54a60b0894cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pillow >=9.4.0
    - traitlets >=5.9.0
    - ipywidgets >=7.7.0
    - requests >=2.28.0
    - ipykernel
    - pandas
    - ipyvuetify
    - ipytree
    - ipyevents
    - plotly
    - ipyleaflet

test:
  imports:
    - vois
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/vois/
  summary: A Python Voilà simplification library
  dev_url: https://github.com/DavideDeMarchi/vois/
  license: CC-BY-SA-3.0
  license_file: LICENCE

extra:
  recipe-maintainers:
    - DavideDeMarchi
